### ISSUE TITLE
Only works with Node 12

### ISSUE THREAD

**Issue by drmikecrowe** [Tombarr/podcast-feed-parser#1]
Is there a reason it  has node-12 specific code and is not node-10 compatible?  

Need to update docs to note this.

Specific line: [.flat()](https://github.com/Tombarr/podcast-feed-parser/blob/master/index.js#L175)

**Comment by Tombarr** [comment]
I bumped to Node 12 since I'm using Erbium LTS across all of my applications. `Array.flat` could be [optionally poly-filled](https://github.com/jonathantneal/array-flat-polyfill/blob/master/src/polyfill-flat.js) or replaced for backwards compatibility, if you'd like to open a PR. I just don't want to introduce a transpiler/ build process unless it adds significant value.

**Comment by Tombarr** [comment]
Clarifies node engine requirement in package.json
